// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ProtoFeatureable is an autogenerated mock type for the ProtoFeatureable type
type ProtoFeatureable struct {
	mock.Mock
}

type mockConstructorTestingTNewProtoFeatureable interface {
	mock.TestingT
	Cleanup(func())
}

// NewProtoFeatureable creates a new instance of ProtoFeatureable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProtoFeatureable(t mockConstructorTestingTNewProtoFeatureable) *ProtoFeatureable {
	mock := &ProtoFeatureable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
