// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/fikrirnurhidayat/ffgo/internal/domain/v1"
	mock "github.com/stretchr/testify/mock"
)

// AudienceEventEmitter is an autogenerated mock type for the AudienceEventEmitter type
type AudienceEventEmitter struct {
	mock.Mock
}

// EmitCreatedEvent provides a mock function with given fields: _a0, _a1
func (_m *AudienceEventEmitter) EmitCreatedEvent(_a0 context.Context, _a1 *domain.AudienceCreatedEvent) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AudienceCreatedEvent) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmitDeletedEvent provides a mock function with given fields: _a0, _a1
func (_m *AudienceEventEmitter) EmitDeletedEvent(_a0 context.Context, _a1 *domain.AudienceDeletedEvent) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AudienceDeletedEvent) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmitGottenEvent provides a mock function with given fields: _a0, _a1
func (_m *AudienceEventEmitter) EmitGottenEvent(_a0 context.Context, _a1 *domain.AudienceGottenEvent) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AudienceGottenEvent) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmitListedEvent provides a mock function with given fields: _a0, _a1
func (_m *AudienceEventEmitter) EmitListedEvent(_a0 context.Context, _a1 *domain.AudienceListedEvent) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AudienceListedEvent) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmitUpdatedEvent provides a mock function with given fields: _a0, _a1
func (_m *AudienceEventEmitter) EmitUpdatedEvent(_a0 context.Context, _a1 *domain.AudienceUpdatedEvent) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AudienceUpdatedEvent) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAudienceEventEmitter interface {
	mock.TestingT
	Cleanup(func())
}

// NewAudienceEventEmitter creates a new instance of AudienceEventEmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAudienceEventEmitter(t mockConstructorTestingTNewAudienceEventEmitter) *AudienceEventEmitter {
	mock := &AudienceEventEmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
