// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/fikrirnurhidayat/ffgo/internal/domain/v1"
	mock "github.com/stretchr/testify/mock"
)

// AudienceListable is an autogenerated mock type for the AudienceListable type
type AudienceListable struct {
	mock.Mock
}

// Call provides a mock function with given fields: _a0, _a1
func (_m *AudienceListable) Call(_a0 context.Context, _a1 *domain.ListAudiencesParams) (*domain.ListAudiencesResult, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *domain.ListAudiencesResult
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ListAudiencesParams) *domain.ListAudiencesResult); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ListAudiencesResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.ListAudiencesParams) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAudienceListable interface {
	mock.TestingT
	Cleanup(func())
}

// NewAudienceListable creates a new instance of AudienceListable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAudienceListable(t mockConstructorTestingTNewAudienceListable) *AudienceListable {
	mock := &AudienceListable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
