// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AudienceResultable is an autogenerated mock type for the AudienceResultable type
type AudienceResultable struct {
	mock.Mock
}

type mockConstructorTestingTNewAudienceResultable interface {
	mock.TestingT
	Cleanup(func())
}

// NewAudienceResultable creates a new instance of AudienceResultable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAudienceResultable(t mockConstructorTestingTNewAudienceResultable) *AudienceResultable {
	mock := &AudienceResultable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
