// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/fikrirnurhidayat/ffgo/internal/domain/v1"
	mock "github.com/stretchr/testify/mock"
)

// Block is an autogenerated mock type for the Block type
type Block struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *Block) Execute(_a0 domain.Repository) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Repository) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewBlock interface {
	mock.TestingT
	Cleanup(func())
}

// NewBlock creates a new instance of Block. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBlock(t mockConstructorTestingTNewBlock) *Block {
	mock := &Block{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
