// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/fikrirnurhidayat/ffgo/internal/domain/v1"
	mock "github.com/stretchr/testify/mock"
)

// FeatureGetable is an autogenerated mock type for the FeatureGetable type
type FeatureGetable struct {
	mock.Mock
}

// Call provides a mock function with given fields: _a0, _a1
func (_m *FeatureGetable) Call(_a0 context.Context, _a1 *domain.GetFeatureParams) (*domain.GetFeatureResult, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *domain.GetFeatureResult
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GetFeatureParams) *domain.GetFeatureResult); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetFeatureResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.GetFeatureParams) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFeatureGetable interface {
	mock.TestingT
	Cleanup(func())
}

// NewFeatureGetable creates a new instance of FeatureGetable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFeatureGetable(t mockConstructorTestingTNewFeatureGetable) *FeatureGetable {
	mock := &FeatureGetable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
