// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/fikrirnurhidayat/ffgo/internal/domain/v1"
	mock "github.com/stretchr/testify/mock"
)

// FeatureUpdatable is an autogenerated mock type for the FeatureUpdatable type
type FeatureUpdatable struct {
	mock.Mock
}

// Call provides a mock function with given fields: _a0, _a1
func (_m *FeatureUpdatable) Call(_a0 context.Context, _a1 *domain.UpdateFeatureParams) (*domain.UpdateFeatureResult, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *domain.UpdateFeatureResult
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UpdateFeatureParams) *domain.UpdateFeatureResult); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UpdateFeatureResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.UpdateFeatureParams) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFeatureUpdatable interface {
	mock.TestingT
	Cleanup(func())
}

// NewFeatureUpdatable creates a new instance of FeatureUpdatable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFeatureUpdatable(t mockConstructorTestingTNewFeatureUpdatable) *FeatureUpdatable {
	mock := &FeatureUpdatable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
