// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/fikrirnurhidayat/ffgo/internal/domain/v1"
	mock "github.com/stretchr/testify/mock"
)

// FeaturesListable is an autogenerated mock type for the FeaturesListable type
type FeaturesListable struct {
	mock.Mock
}

// Call provides a mock function with given fields: _a0, _a1
func (_m *FeaturesListable) Call(_a0 context.Context, _a1 *domain.ListFeaturesParams) (*domain.ListFeaturesResult, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *domain.ListFeaturesResult
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ListFeaturesParams) *domain.ListFeaturesResult); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ListFeaturesResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.ListFeaturesParams) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFeaturesListable interface {
	mock.TestingT
	Cleanup(func())
}

// NewFeaturesListable creates a new instance of FeaturesListable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFeaturesListable(t mockConstructorTestingTNewFeaturesListable) *FeaturesListable {
	mock := &FeaturesListable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
